[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
friendtech_shares = "EKHiWwKJvwP5EWDHy7oZfmgqwaUvxCQ7WP65ZKymQcX5"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
